import type { Conversation, InboxMessage } from './inbox-types';
export const demoConversations: Conversation[] = [
  {
    id: 'sample-ava',
    agencyId: 'demo-atlas',
    connectionId: 'demo-number-1',
    contactPhone: '+000 000 101',
    name: 'Ava Karim',
    service: 'flight',
    destination: 'Erbil → Istanbul',
    inquiryStatus: 'new',
    note: 'Two travelers. Prefers a morning departure.',
    lastInboundAt: '2026-10-08T09:24:00Z',
    lastMessageAt: '2026-10-08T09:24:00Z',
    connectionLabel: 'Atlas main line',
    displayPhone: '+000 000 001',
    preview: 'A morning flight would be perfect. What are our options?',
  },
  {
    id: 'sample-rebaz',
    agencyId: 'demo-atlas',
    connectionId: 'demo-number-1',
    contactPhone: '+000 000 102',
    name: 'Rebaz Ali',
    service: 'visa',
    destination: 'Dubai',
    inquiryStatus: 'inProgress',
    note: 'Checking the required documents for a tourist visa.',
    lastInboundAt: '2026-10-08T08:45:00Z',
    lastMessageAt: '2026-10-08T09:10:00Z',
    connectionLabel: 'Atlas main line',
    displayPhone: '+000 000 001',
    preview: 'I’ll check the documents and get back to you.',
  },
  {
    id: 'sample-noor',
    agencyId: 'demo-atlas',
    connectionId: 'demo-number-1',
    contactPhone: '+000 000 103',
    name: 'Noor Hassan',
    service: 'hotel',
    destination: 'Antalya',
    inquiryStatus: 'closed',
    note: 'Hotel options shared. Customer will confirm their travel dates.',
    lastInboundAt: '2026-10-07T13:10:00Z',
    lastMessageAt: '2026-10-07T13:10:00Z',
    connectionLabel: 'Atlas main line',
    displayPhone: '+000 000 001',
    preview: 'Thank you! I’ll confirm the dates with my family.',
  },
  {
    id: 'sample-dilan',
    agencyId: 'demo-zagros',
    connectionId: 'demo-number-2',
    contactPhone: '+000 000 104',
    name: 'Dilan Azad',
    service: 'package',
    destination: 'Istanbul',
    inquiryStatus: 'new',
    note: '',
    lastInboundAt: '2026-10-08T09:00:00Z',
    lastMessageAt: '2026-10-08T09:00:00Z',
    connectionLabel: 'Zagros main line',
    displayPhone: '+000 000 002',
    preview: 'سڵاو، پاکێجی گەشت بۆ ئیستانبوڵتان هەیە؟',
  },
];
export const demoMessages: Record<string, InboxMessage[]> = {
  'sample-ava': [
    {
      id: 'sample-msg-1',
      direction: 'inbound',
      type: 'text',
      body: 'Hi! We’re looking for two return tickets from Erbil to Istanbul, October 22–28.',
      deliveryStatus: 'received',
      timestamp: '2026-10-08T09:15:00Z',
    },
    {
      id: 'sample-msg-2',
      direction: 'outbound',
      type: 'text',
      body: 'Hi Ava, happy to help! Do you have a preferred departure time?',
      deliveryStatus: 'read',
      timestamp: '2026-10-08T09:18:00Z',
    },
    {
      id: 'sample-msg-3',
      direction: 'inbound',
      type: 'text',
      body: 'A morning flight would be perfect. What are our options?',
      deliveryStatus: 'received',
      timestamp: '2026-10-08T09:24:00Z',
    },
  ],
  'sample-rebaz': [
    {
      id: 'sample-msg-4',
      direction: 'inbound',
      type: 'text',
      body: 'سڵاو، بۆ ڤیزای گەشتیاری دوبەی چ بەڵگەنامەیەک پێویستە؟',
      deliveryStatus: 'received',
      timestamp: '2026-10-08T08:45:00Z',
    },
    {
      id: 'sample-msg-5',
      direction: 'outbound',
      type: 'text',
      body: 'I’ll check the documents and get back to you.',
      deliveryStatus: 'delivered',
      timestamp: '2026-10-08T09:10:00Z',
    },
  ],
  'sample-noor': [
    {
      id: 'sample-msg-6',
      direction: 'inbound',
      type: 'text',
      body: 'Thank you! I’ll confirm the dates with my family.',
      deliveryStatus: 'received',
      timestamp: '2026-10-07T13:10:00Z',
    },
  ],
  'sample-dilan': [
    {
      id: 'sample-msg-7',
      direction: 'inbound',
      type: 'text',
      body: 'سڵاو، پاکێجی گەشت بۆ ئیستانبوڵتان هەیە؟',
      deliveryStatus: 'received',
      timestamp: '2026-10-08T09:00:00Z',
    },
  ],
};
